title: Super Vegetariano
email: your-email@example.com
description: >- 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://supervegetariano.com.mx" 

markdown: kramdown

sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections_dir: _data

collections:
  - addresses
